Dealeron.SalesTax/Models/PurchasedItem.cs
using Dealeron.SalesTax.Helpers;
using System.ComponentModel.DataAnnotations;

namespace Dealeron.SalesTax.Models
{
    public class PurchasedItem
    {
        [Display(Name = "Description", ResourceType = typeof(Resources.Resource))]
        public string Description { get; set; }

        [Display(Name = "Import", ResourceType = typeof(Resources.Resource))]
        public bool ImportProduct { get; set; }

        [Display(Name = "Price", ResourceType = typeof(Resources.Resource))]
        public decimal UnitPrice { get; set; }

        public ItemCategory Category { get; set; }

        public decimal TaxPercentage { get; set; }

        public decimal TotalTaxAmount { get; set; }

        public decimal TaxAmount { get; set; }

        public decimal TotalUnitPrice { get; set; }

        public int Quantity { get; set; }


    }
}

Dealeron.SalesTax/Models/PurchasedItemsModel.cs
using FluentValidation;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Dealeron.SalesTax.Models
{
    public class PurchasedItemsViewModel
    {
        public PurchasedItemsViewModel()
        {
            PurchasedItems = GetDefaultPurchasedItems();
        }

        private List<PurchasedItem> GetDefaultPurchasedItems()
        {
            return new List<PurchasedItem>()
            {
                new PurchasedItem() { Description ="Imported bottle of perfume", Category = Helpers.ItemCategory.Other, ImportProduct=true, UnitPrice=27.99m },
             new PurchasedItem() { Description ="Bottle of perfume", Category = Helpers.ItemCategory.Other, ImportProduct=false, UnitPrice=18.99m },
             new PurchasedItem() { Description ="Packet of headache pills", Category = Helpers.ItemCategory.Medical, ImportProduct=false, UnitPrice=9.75m },
             new PurchasedItem() { Description ="Imported box of chocolates", Category = Helpers.ItemCategory.Food, ImportProduct=true, UnitPrice=11.25m },
             new PurchasedItem() { Description ="Imported box of chocolates", Category = Helpers.ItemCategory.Food, ImportProduct=true, UnitPrice=11.25m },
            };
        }

        public List<PurchasedItem> PurchasedItems { get; set; }
    }
    public class PurchasedItemsViewModelValidator : AbstractValidator<PurchasedItemsViewModel>
    {
        public PurchasedItemsViewModelValidator()
        {

            RuleFor(m => m.PurchasedItems)
                .Cascade(CascadeMode.StopOnFirstFailure)
                .NotEmpty().WithMessage(x => Resources.Resource.PurchasedItemExist)
                .Must(PurchasedItemExist).WithMessage(x => Resources.Resource.PurchasedItemExist);
        }

        private bool PurchasedItemExist(List<PurchasedItem> arg)
        {
            return arg.Count() > 0;
        }
    }
    public class ReceiptViewModel
    {
        public ReceiptViewModel()
        {
            PurchasedItems = new List<PurchasedItem>();
        }
        public List<PurchasedItem> PurchasedItems { get; set; }

        public decimal TotalTaxAmount { get; set; }

        public decimal TotalAmount { get; set; }
    }
}

Dealeron.SalesTax/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Dealeron.SalesTax.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Dealeron.SalesTax/Controllers/PurchaseController.cs
using Dealeron.SalesTax.Helpers;
using Dealeron.SalesTax.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Dealeron.SalesTax.Controllers
{
    public class PurchaseController : Controller
    {
        // GET: Purchase
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult New()
        {
            return View(new PurchasedItemsViewModel());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult New(PurchasedItemsViewModel model)
        {
            IReceiptHelper receipt = new ReceiptHelper(model);

            if (ModelState.IsValid)
            {
                if (receipt.ProcessReceipt())
                {
                    return View("Receipt", receipt.ReceiptModel);
                }
            }
            
            return View(model);
        }


        public ActionResult AddPurchasedItem()
        {
            var itemModel = new PurchasedItem();
            return PartialView("~/Views/Shared/EditorTemplates/AddPurchasedItem.cshtml", itemModel);
        }
    }
}

Dealeron.SalesTax/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Dealeron.SalesTax/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Dealeron.SalesTax/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="http://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

Dealeron.SalesTax/Views/Purchase/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

Dealeron.SalesTax/Views/Purchase/New.cshtml
@model Dealeron.SalesTax.Models.PurchasedItemsViewModel
@{
    ViewBag.Title = "Shopping";
}


<div class="container">
    <div class="col-lg-10 col-md-10 col-sm-10 content-area">
        @using (Html.BeginForm("New", "Purchase", null, FormMethod.Post, new { role = "form" }))
        {
            <div class="text-center"><h2>List of Purchased Items</h2></div>
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div id="purchaseditems">
                @if (Model.PurchasedItems.Count == 0)
                {
                    var purchasedItemViewDataDic = new ViewDataDictionary(ViewData);
                    purchasedItemViewDataDic.Add("AllowDelete", false);
                    @Html.Partial("~/Views/Shared/EditorTemplates/AddPurchasedItem.cshtml", new Dealeron.SalesTax.Models.PurchasedItem(), purchasedItemViewDataDic)
                }
                else
                {
                    foreach (var m in Model.PurchasedItems)
                    {
                        var i = Model.PurchasedItems.IndexOf(m);
                        
                            @Html.Partial("~/Views/Shared/EditorTemplates/AddPurchasedItem.cshtml", Model.PurchasedItems[i])
                        
                    }
                }
            </div>
            <div class="row">
                @Html.ActionLink(@Dealeron.SalesTax.Resources.Resource.AddItem, "AddPurchasedItem", null, new { id= "addPurchasedItemViaAjaxId", @class = "btn btn-lg btn-primary pull-right" })
            </div>
            <br />
            <hr />
            <div class="form-group row">
                <div class="col-md-10">
                    <input type="submit" value="@Dealeron.SalesTax.Resources.Resource.Checkout" id="submitButton" class="btn btn-lg btn-primary pull-right"/>
                    
                </div>
            </div>
        }
    </div>
</div>
<script>
    $("#addPurchasedItemViaAjaxId").click(function () {
        $.ajax({
            url: this.href,
            cache: false,
            success: function (html) {
                $("#purchaseditems").append(html);
            }
        });
        return false;
    });
</script>

Dealeron.SalesTax/Views/Purchase/Receipt.cshtml
@model Dealeron.SalesTax.Models.ReceiptViewModel

@{
    ViewBag.Title = "Receipt";
}

<div class="container">
    <div class="col-lg-10 col-md-10 col-sm-10 content-area" style="margin-top:50px">
        @if (Model.PurchasedItems.Count == 0)
        {
            <p class="order-text">You have not scanned any item. Please go back and scan items at your basket. </p>

            @Html.ActionLink(Dealeron.SalesTax.Resources.Resource.GoBack, "New");
        }
        else
        {
            <h3><strong>Receipt</strong></h3>
            <hr />
            foreach (Dealeron.SalesTax.Models.PurchasedItem item in Model.PurchasedItems)
            {
                <div class="row">
                    <div class="col-md-6"><p class="order-text">@item.Description: </p></div>
                    <div class="col-md-6"><p class="order-text"> <span class="order-data pull-right">@item.TotalUnitPrice @(item.Quantity > 1 ? "(" + item.Quantity + " @ " + item.TotalUnitPrice/item.Quantity + ")" : "")</span> </p></div>
                </div>
            }
            <div class="row">
                <div class="col-md-6"><p class="order-text">Sales Taxes:  </p></div>
                <div class="col-md-6"><p class="order-text"> <span class="order-data pull-right">@Model.TotalTaxAmount</span> </p></div>
            </div>
            <div class="row">
                <div class="col-md-6"><p class="order-text">Total:  </p></div>
                <div class="col-md-6"><p class="order-text"> <span class="order-data pull-right">@Model.TotalAmount</span> </p></div>
            </div>
        }
       
    </div>
</div>

Dealeron.SalesTax/Views/Shared/EditorTemplates/AddPurchasedItem.cshtml
@using MVC.Series.Web.Extensions
@model Dealeron.SalesTax.Models.PurchasedItem
<div class="row" id="purchasedItemRow">
    <div class="col-lg-12 col-md-12 col-sm-12">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <div class="col-md-8">

                    <h3 class="panel-title">Item Information</h3>
                </div>
                
            </div>
            <div class="panel-body form-panel">
                @using (Html.BeginCollectionItem("PurchasedItems"))
                {
                    <div class="form-group row">
                        <div class="col-lg-5 col-md-5 col-sm-5">
                            @Html.LabelFor(m => m.Description, htmlAttributes: new { @class = "" })
                            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger alert-danger" })
                        </div>
                        <div class="col-lg-7 col-md-7 col-sm-7">
                            @Html.TextBoxFor(model => model.Description, new { @class = "form-control" })
                            @Html.HiddenFor(x => x.Description)
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-lg-5 col-md-5 col-sm-5">
                            @Html.LabelFor(m => m.Category, htmlAttributes: new { @class = "" })
                            @Html.ValidationMessageFor(model => model.Category, "", new { @class = "text-danger alert-danger" })
                        </div>
                        <div class="col-lg-7 col-md-7 col-sm-7">
                            @Html.EnumDropDownListFor(model => model.Category, new { @class = "form-control" })
                            @Html.HiddenFor(x => x.Category)
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-lg-5 col-md-5 col-sm-5">
                            @Html.LabelFor(m => m.UnitPrice, htmlAttributes: new { @class = "" })
                            @Html.ValidationMessageFor(model => model.UnitPrice, "", new { @class = "text-danger alert-danger" })
                        </div>
                        <div class="col-lg-7 col-md-7 col-sm-7">
                            @Html.TextBoxFor(model => model.UnitPrice, new { @class = "form-control" })
                            @Html.HiddenFor(x => x.UnitPrice)
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-lg-5 col-md-5 col-sm-5">
                            @Html.CheckBoxFor(model => model.ImportProduct)<span style="font-weight:bold;"> @Dealeron.SalesTax.Resources.Resource.Import</span>
                            @Html.HiddenFor(x => x.ImportProduct)
                        </div>
                    </div>
                    if (ViewData["AllowDelete"] ==null)
                    {
                        <div class="form-group row">
                            <div class="col-md-5"><a class="btn btn-danger" href="#purchasedItemFormGroup" onclick="if ($('#purchaseditems').children().length > 1) { $(this).closest('#purchasedItemRow').remove(); }">Remove Item</a></div>
                        </div>
                    }

                }
            </div>
        </div>
    </div>
</div>

Dealeron.SalesTax/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
          
           
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Sales PRO</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>